version: '3.8'
networks:
  proxy_network:
    external: false
services:
  moodle:
    image: rougeo/sg-php:7.4-apache
    depends_on:
      - mysql
    networks:
      - default
      - proxy_network
    ports:
      - "80:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./share_data:/share_data
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  mysql:
    # container_name: mysql_mooc
    restart: always
    image: mysql:5.7.21
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '3ZVmHEe4N7ANQa'
      MYSQL_USER: 'moodle'
      MYSQL_PASS: '3ZVmHEe4N7ANQa'
    volumes:
      - ./mysql_data:/var/lib/mysql
